#!/usr/bin/env bash
# Generates everything the local secured Kafka stack needs that must not be
# committed: a dev CA, the broker/client/registry keystores, the shared
# truststore, random passwords for all of them, and the config files that use them.
#
# Outputs (all git-ignored):
#   docker/certs/*.jks, ca-*, *.crt, *.csr, broker_*_creds   keys and stores
#   docker/certs/admin-sasl-ssl.properties                   Kafka CLI client config
#   docker/.env                                              the passwords, read by
#                                                            Docker Compose and the app
set -euo pipefail
cd "$(dirname "$0")"

# Git Bash on Windows rewrites arguments that start with "/" (like openssl's
# -subj "/CN=...") into file paths. This turns that off; it does nothing elsewhere.
export MSYS_NO_PATHCONV=1

ENV_FILE=../.env
VALIDITY=3650

new_password() { openssl rand -hex 16; }

CA_PASS=$(new_password)
BROKER_KS_PASS=$(new_password)
CLIENT_KS_PASS=$(new_password)
REGISTRY_KS_PASS=$(new_password)
TRUSTSTORE_PASS=$(new_password)

# The KDC database is created once with its master password, so a re-run keeps
# the existing one instead of inventing a value that no longer matches it.
KDC_MASTER_PASS=$(grep -s '^KDC_MASTER_PASSWORD=' "$ENV_FILE" | cut -d= -f2- || true)
KDC_MASTER_PASS=${KDC_MASTER_PASS:-$(new_password)}

# Same reasoning as the KDC password: postgres only runs init-topic-counts.sql once, against an
# empty data volume, using whatever POSTGRES_PASSWORD it's given at that moment. A re-run here
# must keep that value, not invent one the existing volume no longer matches.
POSTGRES_PASS=$(grep -s '^POSTGRES_PASSWORD=' "$ENV_FILE" | cut -d= -f2- || true)
POSTGRES_PASS=${POSTGRES_PASS:-$(new_password)}

rm -f *.jks *.pem *.crt *.csr *.srl *.key

echo "== Generating CA =="
openssl req -new -x509 -keyout ca-key -out ca-cert -days $VALIDITY \
  -subj "/CN=kafka-dev-ca/OU=Dev/O=Practice/L=City/ST=State/C=US" \
  -passout pass:$CA_PASS

gen_identity() {
  local name=$1        # e.g. broker / client
  local ks_pass=$2
  local cn=$3
  local sans=$4

  echo "== Generating keystore for $name =="
  keytool -genkeypair -keystore "$name.keystore.jks" -alias "$name" \
    -validity $VALIDITY -keyalg RSA -keysize 2048 \
    -storepass "$ks_pass" -keypass "$ks_pass" \
    -dname "CN=$cn,OU=Dev,O=Practice,L=City,ST=State,C=US" \
    -ext "SAN=$sans" -noprompt

  keytool -certreq -keystore "$name.keystore.jks" -alias "$name" \
    -file "$name.csr" -storepass "$ks_pass" -noprompt

  printf "subjectAltName=%s" "$sans" > "$name-ext.cnf"
  openssl x509 -req -CA ca-cert -CAkey ca-key -in "$name.csr" \
    -out "$name-signed.crt" -days $VALIDITY -CAcreateserial \
    -passin pass:$CA_PASS \
    -extfile "$name-ext.cnf"

  keytool -importcert -keystore "$name.keystore.jks" -alias caroot \
    -file ca-cert -storepass "$ks_pass" -noprompt
  keytool -importcert -keystore "$name.keystore.jks" -alias "$name" \
    -file "$name-signed.crt" -storepass "$ks_pass" -noprompt
}

gen_identity broker "$BROKER_KS_PASS" "kafka-broker" "DNS:localhost,DNS:kafka,IP:127.0.0.1"
gen_identity client "$CLIENT_KS_PASS" "kafka-client" "DNS:localhost"
gen_identity registry "$REGISTRY_KS_PASS" "schema-registry" "DNS:localhost"

echo "== Generating shared truststore (trusts our CA) =="
keytool -importcert -keystore truststore.jks -alias caroot \
  -file ca-cert -storepass "$TRUSTSTORE_PASS" -noprompt

echo "== Writing the credential files the Confluent broker image reads =="
# No trailing newline: the image uses each file's contents as the password.
printf '%s' "$BROKER_KS_PASS" > broker_keystore_creds
printf '%s' "$BROKER_KS_PASS" > broker_key_creds
printf '%s' "$TRUSTSTORE_PASS" > broker_truststore_creds

echo "== Writing $ENV_FILE (git-ignored) =="
# Owner-only: only the host reads this file (Docker Compose and the app). The other
# generated files stay default-readable because the containers read them.
(
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by docker/certs/generate-certs.sh. Git-ignored: never commit this file.
KAFKA_CA_PASSWORD=$CA_PASS
KAFKA_BROKER_KEYSTORE_PASSWORD=$BROKER_KS_PASS
KAFKA_CLIENT_KEYSTORE_PASSWORD=$CLIENT_KS_PASS
KAFKA_REGISTRY_KEYSTORE_PASSWORD=$REGISTRY_KS_PASS
KAFKA_TRUSTSTORE_PASSWORD=$TRUSTSTORE_PASS
KDC_MASTER_PASSWORD=$KDC_MASTER_PASS
POSTGRES_PASSWORD=$POSTGRES_PASS
EOF
)

echo "== Writing the Kafka CLI client config (used by init-topics.sh) =="
cat > admin-sasl-ssl.properties <<EOF
security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
ssl.truststore.location=/etc/kafka/secrets/truststore.jks
ssl.truststore.password=$TRUSTSTORE_PASS
ssl.keystore.location=/etc/kafka/secrets/client.keystore.jks
ssl.keystore.password=$CLIENT_KS_PASS
ssl.key.password=$CLIENT_KS_PASS
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/kafka/kerberos/keytabs/kafka.keytab" principal="kafka/localhost@EXAMPLE.COM";
EOF

echo "Done. Files written to $(pwd)"
ls -la *.jks
